version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=host.docker.internal  # For Docker Desktop to reach host
      - DB_PORT=5432  # Changed from 5433 to 5432
      - DB_USER=postgres
      - DB_PASSWORD=fuckoff
      - DB_NAME=sakila
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - HOST=0.0.0.0
      - PORT=8000
      - LOG_LEVEL=INFO
    volumes:
      - ../app:/app/app